### ISSUE TITLE
Launch the MyST -> Jupyter Book parity project

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/mystmd#1001]
To begin, we'd like to communicate our intent to use MyST as a Jupyter Book build engine, and define the basic framework for organizing and prioritizing our work internally.

### Progress towards goal

This is the first step towards the following goal:

- https://github.com/executablebooks/mystmd/issues/1000

This will give us a foundation to begin iterating, with the goal of getting new functionality in front of users as quickly as we can so that we can learn and improve with them.

### Outputs

- Blog post about Jupyter Book 2
    - [Blog draft](https://docs.google.com/document/d/1h4vsUD-vAjFrHVwD6ZMcXZRo2YJOQYbQQYX93i-RflY/edit)
    - https://github.com/executablebooks/meta/pull/1177/
- JEP
    - pre-proposal: https://github.com/jupyter/enhancement-proposals/issues/122
    - https://github.com/jupyter/enhancement-proposals/pull/123
- [Guiding principles for MyST section](https://mystmd.org/guide/guiding-principles)
- Next initiative: https://github.com/executablebooks/mystmd/issues/1106

### Strategy and coordination

- [x] https://github.com/executablebooks/mystmd/issues/1113
- [x] Add enough information to get started: #1106
- [x] #1146
- [x] Write blog post
- [x] Create JEP for incorporating as Jupyter sub-project: https://github.com/jupyter/enhancement-proposals/pull/123

**Comment by stevejpurves** [comment]
We can still identify and start talking to one or two communities now, or stakeholders in those communities, it doesn't need to be blocked by the blog post but the blog post will be helpful for enabling the message to be better communicated across those communities.

**Comment by agoose77** [comment]
I've removed https://github.com/executablebooks/mystmd/issues/618 from this list, as we've discussed that it should be the responsibility of JB2 to convert Sphinx-style glossaries.

**Comment by colliand** [comment]
2024-05-07. Initiatives Planning. @choldgraf mostly trying to set up some blog posts, getting Angus set up for success. I think we should consider this blocked as we wait for upstream people to review. @jmunroe. Is this something the 2i2c team should move forward? Or is this something entirely tracked in EBP? @choldgraf I guess there are two different pieces here: 1. product level guidance to Angus; 2. organizational leadership...principles to guide that transition and provide external communications. Because Chris as an individual is the lead on that project....I guess we could ghost write copy. @colliand. We need a way to celebrate upstream work performed by individuals on 2i2c's team to be seen as 2i2c's investment in open stream projects.

**Comment by choldgraf** [comment]
Spoke a bit with @agoose77 about this today. We've got the two "guiding principles" issues finished up, one of them is merged and the other we'll leave open and use it as a reference for our development-focused initiative:

- #1106 

The only remaining thing for this one is to get the blog post out. @agoose77 is going to finish up a draft and get feedback from one or two communities and then I think we can post it soon

**Comment by choldgraf** [comment]
### Current status

- We've got a [draft blog post ready to go](https://docs.google.com/document/d/1h4vsUD-vAjFrHVwD6ZMcXZRo2YJOQYbQQYX93i-RflY/edit)
- We've got a JEP pre-proposal ready to go: https://github.com/jupyter/enhancement-proposals/issues/122

The pre-proposal has gotten positive feedback as well, and one person asked if we'd be willing to speak with the software steering council on Monday to answer any questions people may have.

### Current plan

- Attend the SSC meeting on Monday (8am California time)
- If that goes positively, then convert the JEP into markdown and make it a PR
- Link the PR from the blog post, and then post the blog post as well

**Comment by choldgraf** [comment]
OK all - I think the final two outputs of this one are done:

- Blog post announcing jupyter book using mystmd: https://github.com/executablebooks/meta/pull/1177/
- JEP for incorporating as Jupyter sub-project: https://github.com/jupyter/enhancement-proposals/pull/123

I suggest we close this one and focus on the development-oriented initiative here w/ @agoose77 :  

- #1106
