### ISSUE TITLE
Lots of errors when building a book PDF with typst

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/mystmd#1003]
## Description

As a part of #1002 I tried to build my multi-page book as a PDF with Typst, but I ran into a ton of errors for what seem like unsupported directives and such. I'm not doing anything too crazy in that report, but there are likely some things I'm using that may not yet be supported, like `{card}` objects.

I used the following command to capture some of the error output:

```
myst build --typst > tmp.txt 2>&1
```

And the content of `tmp.txt` is full of stuff like:

```
help: error occurred while importing this module
   ┌─ _build/temp/mystvtpp1H/my-document.typ:37:9
   │
37 │ #in
clude "my-document-year3.typ"
   │          ^^^^^^^^^^^^^^^^^^^^^^^

error: expected comma
   ┌─ _build/temp/mystvtpp1H/my-document-year3.typ:83:22
   │
83 │ - We created and hired for five new role
s on our team (links to descriptions of each below):
   │                    
   ^
```

## Issues to resolve

- [ ] https://github.com/executablebooks/mystmd/issues/964
- [ ] https://github.com/executablebooks/mystmd/issues/963
- [x] https://github.com/executablebooks/mystmd/issues/962
- [x] https://github.com/executablebooks/mystmd/pull/999

**Comment by choldgraf** [comment]
I think almost all of the errors are gone after using:

- https://github.com/executablebooks/mystmd/pull/999

However I'm still getting a weird error with typst + latex around defining an "abstract":

```
⛔️ myst.yml 'parts' missing required key: abstract (at myst.yml)
```

And I'm seeing an empty "abstract" section at the top of the document.

**Comment by rowanc1** [comment]
The template you are using requires an abstract. :) And we don't have more templates yet...!

You can add the [key in your frontmatter](https://mystmd.org/guide/frontmatter#available-frontmatter-fields), have a title `abstract` for a section or [add a block](https://mystmd.org/guide/quickstart-myst-documents#add-an-abstract-block).

**Comment by choldgraf** [comment]
Hmm, I did have this in my first page:

```
# Title

+++ {"part": "abstract"}
Abstract content

+++
```

but it wasn't getting picked up

**Comment by choldgraf** [comment]
For the frontmatter, it's not clear to me where I put it. Do I put it in `myst.yml` under the `project:` key? The table in the docs seems to suggest that it is not picked up at the project level:

![CleanShot 2024-03-20 at 10 21 38@2x](https://github.com/executablebooks/mystmd/assets/1839645/7c689f3c-b4ae-4263-8562-eb63e478ec80)

**Comment by choldgraf** [comment]
In addition, when I put the following frontmatter in the first page of my book I get the same error:

```
parts:
  abstract: |
    Testing!
```

**Comment by rowanc1** [comment]
Can you point me to a branch to see where your export is defined (is it on a single page)? The `abstract` key is **page only** (in the frontmatter at the top of a document). If you are exporting in multi-doc mode, I am not actually sure how parts are treated, that is still very much evolving. The current typst template is only really designed for single articles/pages.

**Comment by choldgraf** [comment]
A few links:

- Here's the typst config I've tried: https://github.com/2i2c-org/report-czi-2021/blob/68633fb9d5680429fb3ed10af9e3a576d42993e6/myst.yml#L27-L30
- Here's the first page w/ the `abstract` part defined: https://github.com/2i2c-org/report-czi-2021/blob/main/main.md#2i2c-grant-report-overview

It is sounding to me like the abstract issue is not actually a "bug" it is more like a feature request: "Typst support for multi-page documents."

**Comment by rowanc1** [comment]
I opened a few PRs and created a new example of a typst-book:

- https://github.com/2i2c-org/report-czi-2021/pull/2
- https://github.com/2i2c-org/report-czi-2021/pull/3
- https://github.com/rowanc1/typst-book

Yes, figuring out parts in multi-export is a feature request. Hopefully the report examples are illustrative of where to put the frontmatter, I think we need clearer docs on this as the reference is hard to understand?

The la-preprint typst report template also has a bunch of changes that I haven't got to to improve some of the title block rendering. We published a "pubmatter" about a month ago with a ton of improvements:
https://github.com/typst/packages/pull/373

But haven't worked it back into the templates yet because the publish took time and I lost steam on that thread. 🧵

If you can advise on some places where we can improve the docs to make this clearer that would be really helpful.

**Comment by choldgraf** [comment]
I think for the `parts` and front-matter, the easiest thing is just to have a lot of examples in the docs, just saying "here's an example of defining an abstract in the page's frontmatter" and "here's an example of defining the abstract in the `myst.yml` file" would probably have been enough for me.

**Comment by rowanc1** [comment]
I think that there should be a good `typst-book` template that works, is really good and our community supports. That is the template that is likely most appropriate for your content and the linked repo is my _start_ at that, I wasn't implying for you to develop a template, although that too is possible of course.

Hoping to get the book template better in the coming weeks, and that should work out of the box for your content.

Myst can link to any local template or a template in a git repo that is not managed by us. The PR just points to my start of a template via the git repo.

**Comment by choldgraf** [comment]
ah ok cool I see - I thought you were using the `book-template` as like a "here's how you should have built a template yourself with typst" example.

So how about from here on I use your typst-book template and use that report to drive feature dev there?

**Comment by rowanc1** [comment]
Sure that works -- the repo is only 2 commits and 2 hours old for the record, so please calibrate expectations! But the extra eyes and thinking will help shape it. :) When it is a bit more mature and ready for wider feedback we can transfer it over to `myst-templates`, or whenever is appropriate if we start making issues over there.

**Comment by choldgraf** [comment]
yeah for sure - I'm just proposing this in the name of dogfooding in order to drive cycles of development and enhancement. It already looks nice to me though!

**Comment by rowanc1** [comment]
As the PDF can now be build without errors, I am going to close this issue in favour of more specific follow ups. Feel free to reopen it @choldgraf if you fee that there is more to do on this issue.
