### ISSUE TITLE
Tracking issue for building The Turing Way website with MyST

### ISSUE THREAD

**Issue by agoose77** [executablebooks/mystmd#1006]
We discussed in our weekly meeting that it would be helpful to migrate a few projects to MyST as a means of testing our progress.

This issue is tracking issues related to [The Turing Way](https://the-turing-way.netlify.app/)

c.f. #1002 

### Issues uncovered / related

- [ ] https://github.com/executablebooks/mystmd/issues/618

**Comment by rowanc1** [comment]
@agoose77 I just saw this when I searched. I created a duplicate over in #1336. Sorry, didn't realize we were already tracking!
