### ISSUE TITLE
Typst PDF building fails in a hard-to-identify way

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/mystmd#1021]
When you build a PDF with the `--typst` option, but it fails to build (for example, because `typst` isn't installed) then the logs still make it seem like the PDF was built even though it wasn't. You still see something like:

```
🖨 Rendering typst pdf to _build/pdf/report.pdf
```

It would be easier to debug if we had either a more prominent error message, or an error message that helped the user diagnose what was wrong.

### References 

Some discussion about this here:

- https://discordapp.com/channels/1083088970059096114/1177359316886503464/1220497756129591367

**Comment by rowanc1** [comment]
This is fixed with #1033.
