### ISSUE TITLE
Part extraction bugs

### ISSUE THREAD

**Issue by rowanc1** [executablebooks/mystmd#1050]
There is a duplication bug:

```
# testing

+++ {"part": "abstract"}

this is duplicated
```

![image](https://github.com/executablebooks/mystmd/assets/913249/7ea4d686-da12-44f8-a378-fa1c105c8257)

```
# testing

## Abstract

this is duplicated
```

![image](https://github.com/executablebooks/mystmd/assets/913249/ba14568d-5ec6-4c88-9a27-9e2fecf2165b)

And then an error on a blank block (in the theme in `myst-common`):

```
# testing

+++ {"part": "abstract"}

this is duplicated

+++
```

![image](https://github.com/executablebooks/mystmd/assets/913249/9ff5528d-407c-4457-91df-f9ec18d9a1a9)

**Comment by fwkoch** [comment]
Ok - the first couple examples are happening when there is nothing else in the file except the `abstract`. In these cases, when `extractParts` called `remove`, it was removing the entire tree and therefore failing. That's easy to fix - just add a `cascade: false` failsafe if the entire tree is removed. (We already do this exact thing here: https://github.com/executablebooks/mystmd/blob/main/packages/myst-transforms/src/frontmatter.ts#L84-L88)

For the last case, we should definitely add a `?`: `tree.children?.forEach`. But also, blocks should always have children defined... There's a line here where we explicitly remove empty children: https://github.com/executablebooks/mystmd/blob/main/packages/myst-parser/src/tokensToMyst.ts#L577 - I think leaving the empty array is better?

I made these changes here: https://github.com/executablebooks/mystmd/pull/1055

For this to fully take effect, `myst-theme` will need to consume the changes to `myst-common`

**Comment by fwkoch** [comment]
Version bumps that bring this into the theme are included with this pr: https://github.com/executablebooks/myst-theme/pull/351

**Comment by fwkoch** [comment]
Fixed in the latest release of themes. You may need to `myst clean --templates`!
