### ISSUE TITLE
Standardize on the use of label vs. name for cross-reference IDs in figures and tables

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/mystmd#1068]
When defining unique IDs that can be cross-referenced (e.g. `![](#my-id)`), we:

Sometimes use `name`, e.g.:

`````
```{figure} https://source.unsplash.com/random/400x200?beach,ocean
:name: myFigure
:alt: Random image of the beach or ocean!
:align: center

Relaxing at the beach 🏝 🌊 😎
```
`````

Sometimes use `label`, e.g.:

````
:::{table} This is my table
:label: tbl:here
![](#pd-table)
:::
````

### Suggestion: Just pick one

I find it hard to remember when it's one vs. the other, and it feels like unnecessary mental friction to me. Unless there's a semantic reason to use different words for this, can we just pick one? If we need to support old Sphinx behavior, we can always alias it but raise a warning that it should be re-named in the future.

**Comment by rowanc1** [comment]
Both label or name always work and are aliases of each other. The code standardizes on label, sphinx was inconsistent.

I do think the docs need a pass on being consistent though!
