### ISSUE TITLE
R syntax coloration

### ISSUE THREAD

**Issue by mathisdrn** [executablebooks/mystmd#1079]
No syntax coloration on Notebook running R kernel 

myst -v : 1.1.52

## Description
No syntax coloration on Notebook running R kernel 
Example : https://mathisdrn.github.io/head_coach_dismissal/data-extraction#main

**Comment by rowanc1** [comment]
Thanks @mathisdrn. The [r-syntax highlighter is working (demo)](https://mystmd.org/sandbox?tab=demo&myst=YABgAGAAcgAKAGMAbwB1AG4AdAByAHkAIAA8AC0AIABjACgAIgBFAE4ARwAiACwAIAAiAEUAUwBQACIALAAgACIASQBUAEEAIgAsACAAIgBHAEUAUgAiACwAIAAiAEYAUgBBACIAKQAKAHkAZQBhAHIAIAA8AC0AIABjACgAMgAwADEAOAAsACAAMgAwADEAOQAsACAAMgAwADIAMAAsACAAMgAwADIAMQAsACAAMgAwADIAMgApAAoAbQBhAHQAYwBoAF8AcgBlAHMAdQBsAHQAIAA8AC0AIABmAGIAXwBtAGEAdABjAGgAXwByAGUAcwB1AGwAdABzACgAYwBvAHUAbgB0AHIAeQAgAD0AIABjAG8AdQBuAHQAcgB5ACwAIABnAGUAbgBkAGUAcgAgAD0AIAAiAE0AIgAsACAAcwBlAGEAcwBvAG4AXwBlAG4AZABfAHkAZQBhAHIAIAA9ACAAeQBlAGEAcgAsACAAdABpAGUAcgAgAD0AIAAiADEAcwB0ACIAKQAKAGAAYABgAA%3D%3D), but for some reason not picking up from that notebook. Will continue to look into it!
