### ISSUE TITLE
Improve the developer onboarding documentation

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/mystmd#1081]
As a precursor to highlighting MyST more prominently in the Jupyter Book ecosystem, let's set up some basic developer and contribution documentation so that we can more efficiently deal with increases in attention, and potentially contributions, to the project.

### Definition of done

I don't think this needs to be anything comprehensive, but we need enough clarity so that somebody can arrive at the project and relatively quickly understand how they can engage and learn more.

Let's call this done when there's the following information for contributing:

- Get oriented with the project as a whole, where to learn more, where to discuss, etc.
- Set up a basic development environment for MyST and demo local changes
- Set up a documentation build and make changes to the docs
- Make a change to a web theme

### Actions

- [x] https://github.com/executablebooks/mystmd/pull/1015
- [x] https://github.com/executablebooks/mystmd/pull/967
- [x] https://github.com/executablebooks/mystmd/issues/1014

**Comment by agoose77** [comment]
I think this initiative is now done! Thank you _so much_ to @choldgraf, @roaldarbol, and  @rowanc1 for getting this over the line! :rocket:
