### ISSUE TITLE
Support in-line execution with the `{eval}` role

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/mystmd#1109]
The JupyterLab-MyST tool allows for [executable in-line expressions with an `{eval}` role](https://mystmd.org/guide/quickstart-jupyter-lab-myst#inline-expressions). These are computed at the time a markdown cell is rendered from within JupyterLab.

However when a MyST site is executed with `--execute`, these `evals` are not re-computed.

It would be useful it the `{eval}` role executed its content and inserted the resulting output at build time.

Alternatively, if this is not the desired end behavior, we should clarify best-practices for how to insert dynamic content in-line, and clarify that `{eval}` is only for JupyterLab and not for MyST's CLI.

**Comment by agoose77** [comment]
@choldgraf eval expressions should always be recomputed if the cache is invalidated. Have you seen evidence to the contrary?

**Comment by choldgraf** [comment]
That sounds correct to me!

I was assuming that `{eval}` isn't re-computed within MyST because of your comment here:

> To use eval roles, you need to execute the notebook with jupyterlab-myst, and save the notebook. In future, we'll have tooling to do this as part of a myst build.

**Comment by agoose77** [comment]
> To use eval roles, you need to execute the notebook with jupyterlab-myst, and save the notebook. In future, we'll have tooling to do this as part of a myst build.

Ah! This is the new `--execute` flag :) (it executes cells and exprs)

**Comment by choldgraf** [comment]
Amazing! I added docs about this to a PR in order to clarify that this is possible. Feature enhancements that have already been made are the best 😅
