### ISSUE TITLE
[DOCS] Define our computational content with markdown and use `--execute` when building our site

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/mystmd#1114]
The MyST documentation has [a single `.ipynb` file](https://github.com/executablebooks/mystmd/blob/main/docs/interactive-notebooks.ipynb) and assumes that this file has pre-executed content inside. The docs are built without the `--execute` flag so no computation happens.

I think it would be helpful if we instead converted that to (or added in addition) a **markdown file with computation** and built the documentation with `--execute`. This would make it easier to show off functionality like `{eval}` and `{code-block}`, and ensure that they work as expected.

**Comment by rowanc1** [comment]
Yep, was going to suggest this!

**Comment by choldgraf** [comment]
Cool - I think this could also be accomplished alongside the ReadTheDocs preview issue so that we can preview the computations in our PRs and get a lightweight "integration test for docs" out of it:

- #982

**Comment by choldgraf** [comment]
Also just noting that I have no idea how our docs is actually hosted, so it might be a helpful opportunity for @rowanc1 to show how he implements this if we get it implemented.

**Comment by rowanc1** [comment]
This has been implemented!
