### ISSUE TITLE
Add support for composing MyST configurations

### ISSUE THREAD

**Issue by agoose77** [executablebooks/mystmd#1123]
## Proposal
In a meeting with @rowanc1, it was mentioned that journals might wish to define base configurations that e.g. set attribution information. Rowan also pointed out the value to satellite-like organisations such as 2i2c's community work to define a "base" set of acronyms, glossaries, or other features and have derived MyST projects inherit them.

I think this feature has pertinence to Jupyter Book 2's configuration, which may be as simple as defining a base JB set of defaults.

We should consider a new field in the configuration, e.g. `overlays` or `composes` that defines a set of URIs that resolve to configuration files. 

Whether JB 2 still chooses its own `jupyter-book.yaml` that abstracts this mechanism remains to be seen.

**Comment by choldgraf** [comment]
Oooh yes this is great - this would I think solve the internationalization issues. I also think it leans into the MyST idea of "one source of truth" applied to the config layer.

For one example, I could see 2i2c using this to configure standardized navigation links across all of its websites by defining them in one repository, and re-using them in others.

**Comment by agoose77** [comment]
This has been implemented (and helped improve the Project Pythia onboarding)
