### ISSUE TITLE
Netlify: Darkmode is not preserved

### ISSUE THREAD

**Issue by LecrisUT** [executablebooks/mystmd#1130]
When navigating from page-to-page on https://mystmd.netlify.app/, it seems to reset the darkmode to lightmode. Maybe related to the following error in the console?
![Screenshot_20240418_143538](https://github.com/executablebooks/mystmd/assets/25577083/822f63a8-3f94-4dae-8d92-b75ddf3ad216)

**Comment by LecrisUT** [comment]
Oh, for some reason I thought I didn't see this issue with RTD :shrug: might be misremembering or not testing properly due to the broken navigation.

**Comment by rowanc1** [comment]
Probably because so much else was broken. :)
Thanks again for all your help!
