### ISSUE TITLE
Code cell in blockquote does not execute

### ISSUE THREAD

**Issue by rowanc1** [executablebooks/mystmd#1134]
The following nested code-cell fails execution.

````
```{code-cell} python
hello = "hello"
there = "there"
phrase = f"{hello}, {there}!"
print(phrase)
```
some markdown code example

````
```{code-cell} python
:tags: remove-input
print("This will show output with no input!")
```
````

> ```{code-cell} python
> :tags: remove-input
> print("This will show output with no input!")
> ```

the above block
````

This is the AST:

![image](https://github.com/executablebooks/mystmd/assets/913249/77245af5-9af0-49f7-87a1-633b85ca1296)

The failure:
![image](https://github.com/executablebooks/mystmd/assets/913249/b745754c-4e40-46af-bb89-98a373c58673)

That is the *markdown* cell that we are trying to execute in python.

The selection here:
https://github.com/executablebooks/mystmd/blob/bug/code-block/packages/myst-execute/src/execute.ts#L282

it does not take into account nested blocks, and/or special blocks that should *only* contain a code/output pair.
Instead there is a block that contains a code-cell.

The next error is here:
https://github.com/executablebooks/mystmd/blob/bug/code-block/packages/myst-execute/src/execute.ts#L120

Which I think needs an executable flag on it.

Regardless, needs some more test cases on these nested select cases, and/or being more specific about the block we are filtering for.

**Comment by agoose77** [comment]
Ah, it looks like the selector is wrong
`block:has(code[executable=true]):has(output),inlineExpression`

I hadn't thought about executable nodes being nested inside quotes. I didn't think we wanted to support that kind of usage, but I have not personally given it much thought (and I reckon I'd be in favour of it).

The issue is that our version of `unist-util-select` (and in turn, `unist`) doesn't let us tighten the descendent selector in `has(child)` to `has(> child), which is unfortunate.

I'll give this some cycles on Monday, when I'm back in the office, but anyone else is welcome to tackle it!

**Comment by rowanc1** [comment]
I think there are some quick tightening we can do, including labelling the block on the way through. The other block is actually a markdown cell, which happens to contain a code-cell. Not allowed in Jupyter Notebooks, but probably fine to allow here, and I kinda like that it *should* work.

The other selector should at least look for an executable code cell. That would have made it "work" but the one cell would be executed twice.

I think the better plan is to use the `data: type` [here](https://github.com/executablebooks/mystmd/blob/bug/code-block/packages/myst-directives/src/code.ts#L233) or `kind: code-cell` to make the selection of blocks much clearer and less based on the structure. I think we talked around parts of this before, but forget what we decided!

**Comment by rowanc1** [comment]
@agoose77 I have put together a fix by changing `block.data.type` --> `block.kind`, which is going to specifically select those blocks. It does seem to work and pass various tests, I want @fwkoch's take on this, and I haven't tested with thebe.

I think it is good for the cell kind to be a known attribute of the block.
