### ISSUE TITLE
Html to Latex regression 1.1.56

### ISSUE THREAD

**Issue by dellaert** [executablebooks/mystmd#1161]
I noticed a regression when upgrading from 1.1.55 to 1.1.56, in that now the HTML output in notebooks no longer renders.

$ myst -v
v1.1.56

## Description

`myst build --tex` now throws these errors whereas in 1.1.55 this worked fine
```
⛔️ Unhandled LaTeX conversion for node of "div"
⛔️ Unhandled LaTeX conversion for node of "span"
```

The HTML conversion was put in I think by @rowanc1 to support html output from code in roboticsbook.org, in the conversion to latex. But I guess it broke here :-)

## Proposed solution

 I'll revert to 1.1.55 for now. I believe @rowanc1 will probably know exactlhy what happened and how to fix.

**Comment by agoose77** [comment]
@dellaert Rowan will likely know the context of this, but could you share a reproducer so that I might take a look?

**Comment by rowanc1** [comment]
We did change the HTML parsing to now preserve divs, but potentially there is something else going on. I will get the latex parsing back up and working with these changes shortly!

**Comment by dellaert** [comment]
Thanks @rowanc1 
@agoose77 A full repro is hard for me but an example is https://github.com/gtbook/robotics/blob/main/S31_vacuum_state.ipynb. The output of `pretty`. (Rowan has access to a repo in which the entire book is rendered, which he helped set up).

**Comment by rowanc1** [comment]
I will take a look now @dellaert!

**Comment by rowanc1** [comment]
This will be released tomorrow!
