### ISSUE TITLE
Links to biorxiv trigger a DOI fetch error

### ISSUE THREAD

**Issue by thesamovar** [executablebooks/mystmd#1173]
## Description

MyST version 1.1.56

A link to a biorxiv paper is interpreted as a DOI, but versioning messes it up. For example:

``https://www.biorxiv.org/content/10.1101/2020.11.02.364968v2``

gives the error:

``Could not find DOI "https://doi.org/10.1101/2020.11.02.364968v2" from doi.org as doi:10.1101/2020.11.02.364968v2``

## Proposed solution

You could either remove the v2 at the end, or modify the DOI search pattern so it doesn't pick this up.

**Comment by rowanc1** [comment]
Fix will be released soon!
