### ISSUE TITLE
Embedded notebook content is no longer executable

### ISSUE THREAD

**Issue by fwkoch** [executablebooks/mystmd#1220]
## Description

Previously, embedding notebook output using the `embed` or `figure` directive allowed execution directly on the page where embedded.

In the latest release, this interactivity was accidentally disabled: https://github.com/executablebooks/mystmd/releases/tag/mystmd%401.2.2 - Updates to embedding for cross-project references slightly changed the document structure, but the theme was reliant on the old structure for enabling execution.

## Proposed solution

It should be simple to restore the old structure (this means removing an extra, invisible `block` around the embedded content).

**Comment by choldgraf** [comment]
- closed by https://github.com/executablebooks/mystmd/pull/1221
