### ISSUE TITLE
New TOC should be normaliseable to a TOC without pattern entries

### ISSUE THREAD

**Issue by agoose77** [executablebooks/mystmd#1243]
## Description
The new TOC implements a pattern entry. This is really just shorthand for enumerating files, and we should not have to reason about patterns in our TOC handling logic

## Proposed solution
Normalise a TOC to a TOC without patterns

**Comment by fwkoch** [comment]
There is now a step in the project processing that converts a toc into a toc without patterns. This isn't really visible or available externally, but I don't think it needs to be...? It's just an implementation detail that simplifies subsequent toc handling.
