### ISSUE TITLE
Error to user on files in `project.toc` without extension

### ISSUE THREAD

**Issue by fwkoch** [executablebooks/mystmd#1248]
The project toc is intended to be strict, but we still resolve extensions for entries without extensions (this is behavior left over from the old _toc.yml handling).

When MyST resolves an extension, it should print an error to the user informing them to fix it!

**Comment by rowanc1** [comment]
An additional thing to maybe consider is raising an error if there are multiple choices (e.g. article.tex and article.ipynb). This is something that I ran into recently and had to rename the files to get them both in the old toc!
