### ISSUE TITLE
execution and the `raises-exception` tag

### ISSUE THREAD

**Issue by parmentelat** [executablebooks/mystmd#1256]
with jb1, adding in a cell the `raises-exception` tag allowed execution to proceed even if that cell was crashing

apparently this is not the case with mystmd, is this intentional, do we need to change our input or is it just too early to ask ?

**Comment by rowanc1** [comment]
This isn't implemented quite yet! Thanks for the feature request.

**Comment by agoose77** [comment]
@rowanc1 actually, this _was_ implemented, but I made a mistake! Fix is in #1258

**Comment by parmentelat** [comment]
@agoose77 cool, and thanks for the ultra-fast answer :)
