### ISSUE TITLE
Configuration option to exclude files/patterns

### ISSUE THREAD

**Issue by rossbar** [executablebooks/mystmd#1268]
I've searched the issue tracker and didn't see any issue that *exactly* matched my question... #1228 is certainly related but given the breadth of discussion there I figured it might be easier to open a new discussion - apologies in advance for the clutter!

## Proposal

Sphinx/JB1 has the `exclude_patterns` option in the project configuration to enable ignoring certain files/patterns at build time. AFAICT there is not (yet) equivalent functionality in the `myst.yml` configuration.

## Additional notes

For many cases, I think there are ways this could be worked around by reorganizing directory structures; however IME with JB1 this is a very handy configuration option!

**Comment by agoose77** [comment]
Hi @rossbar, perhaps [the `exclude` frontmatter field](https://mystmd.org/guide/table-of-contents#excluding-files) (`myst.yml`) is what you're looking for?

**Comment by agoose77** [comment]
Closing this as answered :)
