### ISSUE TITLE
Allow --execute to detect kernelspec in ipynb

### ISSUE THREAD

**Issue by scottyhq** [executablebooks/mystmd#1283]
## Proposal

Executing notebooks is a really great feature, thanks! Following these docs (https://mystmd.org/guide/execute-notebooks#how-myst-executes-your-code) I was hoping to be able to point at different kernels for different notebooks. 

Currently (myst v1.2.5) it seems the kernel in which myst is installed is used rather the using whatever is in the notebook metadata? 

A given `notebook.ipynb` has metadata pointing to a specific kernel. But it appears that `myst start --execute` uses whatever the current python environment is rather than checking available kernels or inspecting notebook metatadata.
```
 "metadata": {
  "kernelspec": {
   "display_name": "hypercoast",
   "language": "python",
   "name": "hypercoast"
  },
```

```
# jupyter kernelspec list
Available kernels:
  python3         /Users/scotthenderson/miniforge3/envs/mystmd/share/jupyter/kernels/python3
  hypercoast      /Users/scotthenderson/Library/Jupyter/kernels/hypercoast
  xarray-tests    /Users/scotthenderson/Library/Jupyter/kernels/xarray-tests
```

## Additional notes

`jupyter nbconvert` uses `kernelspec` in `notebook.ipynb` by default, or you can override it: 

`jupyter nbconvert --execute --ExecutePreprocessor.kernel_name=xarray-tests --to html myfigure.ipynb`

see https://nbconvert.readthedocs.io/en/latest/execute_api.html?highlight=kernel_name#execution-arguments-traitlets

**Comment by agoose77** [comment]
We are already looking to where we expect to see the kernelspec defined for a notebook. However, it turns out that this field isn't populated when we read from an ipynb rather than an md file. We will fix this! :)
