### ISSUE TITLE
Logo and favicon should be able to be remote

### ISSUE THREAD

**Issue by rowanc1** [executablebooks/mystmd#1296]
Currently it isn't possible to use remote images for the favicons and logos, that is quite important for shared configuration files.

The important things to be able to be remote are:

- favicon
- logo
- logo_dark

**Comment by jnywong** [comment]
Are we waiting on the favicon to close this? Looking to see if I can merge projectpythia-mystmd/radar-cookbook#2

**Comment by rowanc1** [comment]
I think that is good to go now @jnywong! The favicon will start to work in the next few days, but need not block that work.

**Comment by fwkoch** [comment]
Looking into favicon - there is discrepancy handling this in `myst-cli` vs `myst-theme`:

- In `myst-cli`, `favicon` is a property directly on `SiteConfig`: https://github.com/executablebooks/mystmd/blob/main/packages/myst-config/src/site/types.ts#L31
- In `myst-theme`, `favicon` is handled as a site template option: https://github.com/executablebooks/myst-theme/blob/main/themes/article/template.yml#L35 & https://github.com/executablebooks/myst-theme/blob/main/packages/common/src/utils.ts#L133

So, if you just chuck `favicon` under `site.options` it works fine, including URLs, with the most recent release of myst.

This should be tidied up to either (1) eliminate `favicon` from `SiteConfig` and require all themes to bring in as an option, if desired, or (2) change things on the theme side to respect the top-level `favicon`, not in options. I'm not super opinionated here - I feel like (1) maybe makes slightly more sense, though: Given a theme that does not allow users to customize favicon, it's better to have a warning message on an invalid option than allow users to set favicon in the config that will be totally ignored.

**Comment by agoose77** [comment]
@fwkoch how does MyST handle file-paths in the theme options for favicons? Do we do any prep work to copy the favicon to the static paths?

**Comment by fwkoch** [comment]
This is where all the theme `file` options get downloaded (if remote) and copied to `static` folder: https://github.com/executablebooks/mystmd/blob/main/packages/myst-cli/src/build/site/manifest.ts#L406

That covers `site.options.favicon` if it's defined in the theme.

**Comment by fwkoch** [comment]
Regarding `SiteConfig.favicon`, that will be obsolete if we go through with the changes discussed here: https://github.com/executablebooks/mystmd/issues/1308#issuecomment-2174233550

That field will just _be_ the template option and no longer be defined in the `SiteConfig` type.

**Comment by fwkoch** [comment]
I am going to close this issue:

Favicon must be specified with `site.options.favicon`, and in that case, it may be remote.

`site.favicon` does not work at all, whether it is a local or a remote url. This will be cleaned up as part of #1308
