### ISSUE TITLE
HTML should parse `video` HTML tags

### ISSUE THREAD

**Issue by rowanc1** [executablebooks/mystmd#1297]
Currently we don't parse video html tags. This should be improved to parse the `video` tag.

![image](https://github.com/executablebooks/mystmd/assets/913249/68e7d974-4c49-412b-9fb7-379f87c6c42c)

cc @jnywong

**Comment by rowanc1** [comment]
This has been fixed and should be available shortly. 🚀

**Comment by tuncbkose** [comment]
Are the attributes working in this implementation? I can't seem to get `controls` to display.

Also, in case anyone else encounters this, my video was originally added as
```
<video ...>
  <source ...>
</video>
```
and wasn't showing up but putting it all in `<video ...>` fixed the issue.
