### ISSUE TITLE
`thumbnail` from frontmatter is not honored in `og` `meta` tags

### ISSUE THREAD

**Issue by stevejpurves** [executablebooks/mystmd#1315]
### Describe the bug

**context**
When I build a website that has figures in it and explicitly add a thumbnail to my myst.yml

**expectation**
I expected the thumbnail that I specified `myst.yml` to be preferentially used in the og:image meta tags

**bug**
But instead i see the first figure from my index page appearing as thumbnail

**problem**
This is a problem for people who want to specify the thumbnail

### Reproduce the bug

1. Get a myst site with at least one figure
2. Also specify a thumbnail in the `myst.yml`
3. Use OGraph previewer or check `head` section of html to see that the wrong thumbnail is referenced

**Comment by stevejpurves** [comment]
@fwkoch already has this tracked down 💪🏼

**Comment by fwkoch** [comment]
This was fixed in #1316 and will be in the next release.
