### ISSUE TITLE
During pdf builds custom bibtex tags are not respected

### ISSUE THREAD

**Issue by stevejpurves** [executablebooks/mystmd#1318]
## Description

If an author has their own `bib` file,  `articles.bib`, in which they are using a different tag style e.g. `jones-etal-2014` on their bibtex entries as they prefer `[@jones-etal-2014]` in their manuscript.

Upon building a latex pdf, a `main.bib` file is produced in the `_build/` folder that contains (enriched?) version of the bibtex entries, but with normalized tags e.g. `jonesAdam2014`, yet the tags used in the manuscript in the `_build` folder have not been normalized to match.

## Proposed solution
Either normalize everything, or don't normalize tags at all and respect origin tags used by the author in their bib file?

**Comment by fwkoch** [comment]
This is fixed by https://github.com/executablebooks/mystmd/pull/1322

Updating `citation-js` gives us a nice config option that prevents this implicit label behavior.

**Comment by fwkoch** [comment]
Released with v1.2.9!
