### ISSUE TITLE
Remove `output` directive

### ISSUE THREAD

**Issue by fwkoch** [executablebooks/mystmd#1354]
Previously, when ingesting jupyter notebooks for myst, we created an in-memory markdown "file." For cell outputs, the output data was moved to a cache, keyed off arbitrary `id`, then we used an `output` directive in the markdown "file" with that `id` to inject the output back into the document... Now we just go straight from notebook to mdast; much more straight-forward and understandable, I think.

However, the little `output` directive with only an `id` is still lingering in our `myst-directives` (and the docs!). This directive does not have any user-facing functionality and now has no internal functionality either. I think we should just remove it.

**Comment by stevejpurves** [comment]
@fwkoch is there anything downstream that might be using this? a unist select() one of the themes for example?

https://github.com/executablebooks/myst-theme/blob/ec6cd2b8bf0cb53292e99bf3d2bcb212236fc876/packages/jupyter/src/execute/provider.tsx#L90

**Comment by agoose77** [comment]
@stevejpurves your example is the output AST node which we _do_ use, it's just the directive that's redundant.
