### ISSUE TITLE
Request to install imagemagick blends into the background in dark terminals

### ISSUE THREAD

**Issue by JBorrow** [executablebooks/mystmd#1376]
## Proposal

When trying to build a paper as a pdf, I gave up when I thought that myst couldn't deal with my svgs. Turns out it could, I just missed the 'you should install imagemagick' as the colouring indicates that is not an important message.

I suggest making 'To convert this image, you must install imagemagick' bold, bright, and in-your-face!

![Screenshot 2024-07-10 at 1 24 52 PM](https://github.com/executablebooks/mystmd/assets/7839515/4ca77eca-68f3-44ac-b797-e5274423548b)

**Comment by rowanc1** [comment]
Thanks @JBorrow for the issue!

The place to make the changes are here:
https://github.com/executablebooks/mystmd/blob/main/packages/myst-cli/src/transforms/images.ts#L452

You can change the `note:` line with the main image. Completely agree that the error line should be the action to solve it, with the debug line being the extra information. Might need a bit of rewording as well. :)
