### ISSUE TITLE
Improve the quick start guides

### ISSUE THREAD

**Issue by stevejpurves** [executablebooks/mystmd#153]
Overall the MyST Install and MyST Markdown guides are great 🚀. on the latter I kept looking for / wanting a link to a big reference list of roles and directives that I could play with, in the editor blocks on the page

I struggled with MyST Documents though, the content is great 🙏 but it felt really awkward - the fact that we’re updating document stuff whilst trying to ignore the web view and the ability to. preview changes, makes the whole thing difficult, also confusing as we keep referencing web views throughout the article and showing screenshots of them.

Then on the MyST Website guide I was expecting a full run though -- but it stops after basic setup. Also, seems incomplete as we’re not giving the site and project configuration full treatment?

Overall I think we should restructure the Documents and Website guides to fit the reality that the best way to work with myst-cli is to use the web view and website generation as the writing environment, and put that front and center -- get people to go though setting up their local web preview, modifying content in an article and on a site level, and then move to the document generation given the web preview -- it’l be much easier then to have people preview as they go when making the article level changes, and when we then talk about the document export we can reference and cite the web preview, and explain differences 

in the static formats....
So a running order of something like:
1. MyST Install
2. MyST Websites
3. MyST Documents
4. MyST Website Configuration (advanced)
5. MyST Projects

Where 2. gets people comfortable with myst start and the watch, and goes through most of the article content setup that is currently in MyST Documents.

3. then follows on from that, is shorter focusses on export, templates and perhaps some additional document only frontmatter (like short_title?)

4. goes into sitewide config and 5. introduces project level and multi-project concepts?

I took some additional notes and captured "reactions" as I progressed thought the docs, that is attached as a pdf.
[myst-guide-review.pdf](https://github.com/executablebooks/mystjs/files/10494473/myst-guide-review.pdf)

**Comment by rowanc1** [comment]
Nice -- this is fantastic feedback -- thanks for going through it in detail @stevejpurves, needs a bunch more passes to get it good!!

I think you are seeing that I did a last minute change to split one tutorial into two (and the break is pretty bad with missing figures etc)!

I really like what you started in #150 and will pick those changes up in #152.
