### ISSUE TITLE
Deploy Pages directly from GitHub action

### ISSUE THREAD

**Issue by kolibril13** [executablebooks/mystmd#404]
### Which area is this feature request for?

Other

### Describe the feature you'd like to request

The new static export is awesome!
I really like that it's now possible to host myst notebooks on GitHub pages with super low friction, thanks for making this possible!

To make the setup process even more simple one suggestion:
would it be possible to create the GitHub Pages page directly from the Actions artifact without a gh-pages branch?
When there is no gh-pages branch, this would also keep the repo size small.
![image](https://github.com/executablebooks/mystjs/assets/44469195/56befc22-94fb-4f45-84b7-2dff01035584)

JupyterLite does it that way: https://jupyterlite.readthedocs.io/en/latest/quickstart/deploy.html#generate-a-new-repository-from-the-template
maybe there is a way to bring this also to mystjs

**Comment by rowanc1** [comment]
This has been updated as the default action in `v1.1.0`. Note that previous versions of the action will still mostly work, although you will need to rename `myst-cli` to `mystmd`. See #451.

To update to the new action:

```
myst init --gh-pages
```

And then change your source to `GitHub Actions` for the pages instead of the branch.

**Comment by kolibril13** [comment]
That's amazing, thank you for lowering the barrier to use and share content with myst to such an effortless minimum! :)
I'll try that tomorrow!

**Comment by rowanc1** [comment]
It is much better than having the `gh-pages` branch hanging around!

We have also increased the speed of the CI install by ~17x. 🚀
