### ISSUE TITLE
If myst content contains certain unicode characters, export will break

### ISSUE THREAD

**Issue by stevejpurves** [executablebooks/mystmd#426]
### What version of `mystjs` are you using?

1.0.2

### How did you install myst?

npm

### What operating system are you using?

Mac

### Which area is this feature request for?

Export: Microsoft Word

### Describe the Bug

I have a file with various unicode characters in, in particular these are console/control characters which are of no use.

![image](https://github.com/executablebooks/mystjs/assets/1473646/875190aa-5872-493b-a5a7-4e8c4cf66679)

This results in an invalid file or a file with truncated content.

### Expected Behavior

We should still get an valid output file with all content, either with any control characters stripped out or left to be rendered as some nasty character so that author can remove them.

### To Reproduce

this is a string that holds some of these characters - if github preserves them!

```
The former involves subjecting the as-synthesised carbon to a flow of ammonia at elevated temperatures,{cite:p}`Zhai2016Nitrogen` and/or mixing with nitrogen-containing liquids such as HNO{sub}`3`.{cite:p}`Elmouwahidi2019Influence`{cite:p}`Zhang2019Low` 
```

**Comment by rowanc1** [comment]
#724 will remove these!

**Comment by rowanc1** [comment]
Also -- was not aware that there is an ascii character to make the terminal go ding 🛎!!

https://en.wikipedia.org/wiki/Bell_character
