### ISSUE TITLE
📣 Rename of `myst-cli` to `mystmd`

### ISSUE THREAD

**Issue by rowanc1** [executablebooks/mystmd#451]
The command line tools have been renamed from `myst-cli` to `mystmd`. This is to open up a consistent path in the  _future_ to installing via pip/conda (#139). This also consolidates our terminology and domain rename (e.g. see executablebooks/team-compass#21).

To upgrade to `v1.1.0` of the MyST CLI you will need to:

```bash
npm uninstall -g myst-cli
npm install -g mystmd
```

**For development**

```bash
npm uninstall -g myst-cli
npm run build
npm run dev # This will relink the packages
```

If you have any problems, it may say there is a conflicting `myst` command, delete the file noted in the error log and build again.

**Comment by frenck** [comment]
It was rather surprising to see a breaking change happing in a minor release tbh.

**Comment by rowanc1** [comment]
Thanks for the feedback, sorry this broke something on your end. I hope that the update should be straight forward, if you are on CI, change `myst-cli` to `mystmd` and everything should work again. We are continuing to use the `myst-cli` project for programmatic exports, but the export for the command line tool is no longer included in that npm package. In talking with folks on how to handle the name change we felt a clean break was better than supporting the same `myst` export in two packages, which makes conflicts and would lead to many other install problems.

These are some of the changes that are aiming to take us out of beta over the next few months. You are probably right that this could have been a major release, we will aim to be better in the future.

**Comment by frenck** [comment]
> I hope that the update should be straight forward, if you are on CI, change myst-cli to mystmd and everything should work again.

The fix is easy, that is not the issue, but since it is used in workflows, it just breaks CI for others all of a sudden: Surprise!

> we will aim to be better in the future.

❤️

**Comment by rowanc1** [comment]
I think that you are right about the GitHub action. We should probably maintain an action and release that with its own cadence. Will open an issue.

**Comment by rowanc1** [comment]
Closing now that this is a month old, we have also recently released `mystmd` on `conda` and `pypi`, which we will make an announcement about soon.
