### ISSUE TITLE
Embedded figures without captions fail JATS validation

### ISSUE THREAD

**Issue by rowanc1** [executablebooks/mystmd#471]
Right now the caption has to be at the top of the figure node. If a caption is not included by default, then the embedded source creation creates a caption that is at the bottom of the figure. This isn't valid.

For example:
```
:::{figure} #interactive-output
:::
```

Creates this output

![image](https://github.com/executablebooks/mystmd/assets/913249/29e69ded-6028-4de2-bb7f-82a84072ed7e)

The error:
![image](https://github.com/executablebooks/mystmd/assets/913249/6677b574-968b-4354-a49c-52a2107b0e4b)

**Comment by fwkoch** [comment]
Oh - I realize this generated caption was totally broken by https://github.com/executablebooks/mystmd/pull/477 when I reduced the structure `figure > embed > block > output` -> `figure > output` - that is relied on here: https://github.com/executablebooks/mystmd/blob/main/packages/myst-to-jats/src/transforms/containers.ts#L46-L49 (test coverage 😬).

Gotta revive that, then reproduce this and fix if necessary.
