### ISSUE TITLE
Linking large number of DOI's can fail, and is difficult to debug

### ISSUE THREAD

**Issue by englertr** [executablebooks/mystmd#501]
## Problem
I have a relatively large MD file with >30 DOI links. When building with "myst start", the linking of references either crashes the build or does not link all of the DOI's.

### mystmd version 
v1.1.6, installed with npm
### os
Ubuntu /Mac

## Description
I am working on a manuscript, which is fairly large and has a lot of references (over 30 unique DOI's, a lot of them referenced multiple times). I am adding the DOI's with the full  https links. When building the page with "myst start", one of two things happen:
1. either the build sometimes (not always) crashes at a specific reference:
![image](https://github.com/executablebooks/mystmd/assets/57198205/98e8ea45-a761-41ff-b1f3-4713545ba84d)
(removing this exact reference, prevents this error completely)
 
2. Or I get a seemingly random number of these warnings:
![image](https://github.com/executablebooks/mystmd/assets/57198205/50b881f2-ec1c-4a03-933a-d64c9ca00968)
which then leads of course to missing DOI's in the final document and the references. The unobtainable DOI's are also different each time I try to build. 

I iteratively removed some of the text to find a specific segment that causes the error, but that did not help me to pinpoint the exact  source of the problem unfortunately. However, removing segments in the text that contain a lot of DOI links, seems to prevent both the error from 1 and the warnings from 2. 

## Additional notes
Would you recommend to rather switch to a bibtex file to avoid the dynamical linking of this many DOI's?

Thank you very much in advance!

**Comment by englertr** [comment]
I was able to circumvent both issues by moving the references to a bib file. Cheers!

**Comment by rowanc1** [comment]
Hi @englertr and @lrq3000 -- finally getting around to some of these improvements with caching on DOIs and other links through:

- #913 

@fwkoch's changes seriously speeds up the build process (2s-4s --> 5ms for linking DOIs) and everything feels snappier as these are read locally after they are successful. I am also hopeful that this would have made your problems a bit easier to diagnose and/or move to controlling the bibtex yourself, as the `_build/cache` directory will now list the files easily and could be searched over to see any bibtex that was malformed (which I also ran into the other day!). The changes will be release soon!

Thanks again for your feedback!
