### ISSUE TITLE
Myst user site bug when project name has the word ".github.io" in it

### ISSUE THREAD

**Issue by kolibril13** [executablebooks/mystmd#511]
Just a minor thing:

GitHub allows creating a [user site](https://docs.github.com/en/pages/getting-started-with-github-pages/about-github-pages#types-of-github-pages-sites). From that docs: 

 > To publish a user site, you must create a repository owned by your personal account that's named username.github.io

That means my repo is

https://github.com/kolibril13/kolibril13.github.io

but in myst.yml this becomes 

https://github.com/kolibril13/kolibril13hub.io.git

because the first .git is cropped away by myst.

Same for the gh pages when initializing it with myst init --gh-pages

So the fix would be to just crop the .git part when it's at the end.

<img width="1271" alt="image" src="https://github.com/executablebooks/mystmd/assets/44469195/eaf26de3-98d4-49dd-a789-1a53da897dee">

**Comment by rowanc1** [comment]
Thanks for the report, should be fixed in #512!
