### ISSUE TITLE
A heading fails to parse correctly

### ISSUE THREAD

**Issue by stevejpurves** [executablebooks/mystmd#534]
See the example in the MyST sandbox here: https://mystmd.org/sandbox?tab=demo&myst=YABhAHIAdABpAGMAbABlAC4AKABtAGQALwBxAG0AZAApAGAACgA6ACAAVABoAGkAcwAgAG0AYQByAGsAZABvAHcAbgAgAGYAaQBsAGUAIABhAHQAIAB0AGgAZQAgAHIAbwBvAHQAIABvAGYAIAB0AGgAZQAgAHIAZQBwAG8AcwBpAHQAbwByAHkAIABpAHMAIAB0AGgAZQAgAG0AYQBpAG4AIABtAGEAbgB1AHMAYwByAGkAcAB0ACAAdABoAGEAdAAgAHIAZQBmAGUAcgBlAG4AYwBlAHMAIABhAG4AZAAgAGwAaQBuAGsAcwAgAHQAbwAgAHQAaABlACAAbwB0AGgAZQByACAAbgBvAHQAZQBiAG8AbwBrAHMAIABpAG4AIAB0AGgAZQAgAHIAZQBwAG8AcwBpAHQAbwByAHkALgAgAFQAaABlACAAZgBpAGwAZQBuAGEAbQBlACAAaQBzACAAbgBvAHQAIABmAGkAeABlAGQALAAgAGIAdQB0ACAAaQBmACAAYwBoAGEAbgBnAGUAZAAgAHQAaABlACAAYwBvAG4AZgBpAGcAdQByAGEAdABpAG8AbgAgAGYAaQBsAGUAcwAgAGYAbwByACAAdABoAGUAIABhAHUAdABoAG8AcgBpAG4AZwAgAHQAbwBvAGwAIABzAGgAbwB1AGwAZAAgAGIAZQAgAHUAcABkAGEAdABlAGQAIABhAHAAcAByAG8AcAByAGkAYQB0AGUAbAB5AC4ACgAKACMAIwAjAKAATgBlAHgAdAAgAFMAdABlAHAAcwAKAA%3D%3D

![image](https://github.com/executablebooks/mystmd/assets/1473646/6b6c72ea-26f0-418a-8caa-06a66afc406f)

This snippet was written in VS Code and copied into the sandbox, if we delete the whitespace character between the pound sign and the letter `N` then the heading parses properly.

There is a strange whitespace character not being parsed as expected? this is difficult to reproduce but appears inexplicable and difficult to get out of when it does occur.

**Comment by stevejpurves** [comment]
ok it appears it's nothing to do with the defintion list https://mystmd.org/sandbox?tab=demo&myst=IwAjACMAoABOAGUAeAB0ACAAUwB0AGUAcABzAA%3D%3D

**Comment by rowanc1** [comment]
This looks like a no-break space, which can happen on Alt-Space in a mac. It is annoying that vscode doesn't highlight the space as a different whitespace character. We are using no-break-spaces in latex, which convert to a `~`.

The vscode renderer and GFM do not recognize this as a heading either, so I am tempted to close!
