### ISSUE TITLE
Incorporate execution

### ISSUE THREAD

**Issue by akhmerov** [executablebooks/mystmd#550]
## Proposal

Right now including computation outputs requires creating `.ipynb` files that do contain these outputs. Storing `.ipynb` in git is a nuisance, especially with outputs. By comparison, the sphinx stack includes jupyter-cache that will interpret and execute all code cells in a document. Therefore, authoring experience would be much better if `myst` would integrate with jupyter-cache or provide utilities for execution through any other means.

**Comment by rowanc1** [comment]
Thanks for all the issues @akhmerov, keep them coming. :)
This is absolutely on our roadmap for the project as we improve compatibility with JupyterBook.

**Comment by agoose77** [comment]
Closed by #873!
