### ISSUE TITLE
Thebe Improvements

### ISSUE THREAD

**Issue by rowanc1** [executablebooks/mystmd#557]
- [ ] Remove booleans from the allowed configurations and fill them in at validation time

Currently we allow `{binder: true}` and much of the logic for resolving the option is in the thebe library, not in the frontmatter. I think that we should move the logic for auto creating the configuration to `myst-frontmatter` package in addition to thebe.

- [ ] Allow Thebe Binder Ref to be optional

Currently when setting the `binder:` options on thebe, the reference must be defined, if it isn't thebe fails to create a proper binder URL. We should have a sensible fallback (i.e. `main`) for this option.

**Comment by stevejpurves** [comment]
Confused by removal of booleans in the title but not in the description.
You are saying it should not be possible to set `binder: true` in the
frontmatter? On server:true i agree, but rhe binder option is useful if it
can resolve properly, which we can do.

I beleive a lot of the code to expand options is already in mystmd, so
thebe's defaults and fallbacks should essentially be overridden already,
perhaps thats where improvements need to be made and we can move them to a
better home in the process for sure +1

**Comment by rowanc1** [comment]
I think that we should coerce a boolean into a valid object, rather than saving the option in the JSON. We should still allow users to write `"binder: true"`, but I think we should unpack that into a valid dict early.

frontmatter:
```yaml
---
github: github.com/org/repo
thebe: 'binder'
---
```

Which should get validated to a unpacked config object:
```json
{
"github": "https://github.com/org/repo",
"thebe": {
  "binder": {
    "repo": "org/repo",
    "ref": "HEAD"
  },
},
}
```

Right now it gets unpacked to:
```json
{
"github": "https://github.com/org/repo",
"thebe": {
  "binder": true,
},
}
```

And then the creation of all of the logic of where to pull github from etc. happens in the thebe client, rather than having that happen in the config creation in the CLI.

**Comment by stevejpurves** [comment]
ok that's clear and sounds good!
