### ISSUE TITLE
imgur images

### ISSUE THREAD

**Issue by joamatab** [executablebooks/mystmd#563]
How can we fix imgur images?

![image](https://github.com/executablebooks/mystmd/assets/4514346/fcfd42a3-11d9-4ddc-a69c-dbbee854ad94)

**Comment by fwkoch** [comment]
@joamatab Thanks for posting this! I poked around a bit, and it looks like imgur requires a `user-agent` header or else it just gives back an empty response. This should be a pretty trivial fix in mystmd - I'll get a fix out later today.

**Comment by fwkoch** [comment]
This fix is now in the latest release on npm!

**Comment by joamatab** [comment]
Awesome 😎 thank you
