### ISSUE TITLE
Add kwd-group and permissions frontmatter

### ISSUE THREAD

**Issue by stevejpurves** [executablebooks/mystmd#573]
## Proposal

We'd like to align the JATS frotnmatter tag content as closely as possible with quarto. Quarto currently includes some additional frontmatter fields that are relevant for publication:

* kwd-group
* permissions

## Additional notes
Also relevant is https://github.com/executablebooks/mystmd/issues/572

**Comment by fwkoch** [comment]
Resolved with #596
