### ISSUE TITLE
Node type "glossary" is not properly handled when exporting to PDF

### ISSUE THREAD

**Issue by andry-tino** [executablebooks/mystmd#584]
When working on an MD file which uses the `:::{glossary}` environment, glossary terms are properly emitted when rendering HTML, but they generate an error when exporting to PDF.

Can be reproed in 1.1.15.

## Description
Create a simple MD file:

```
---
title: A simple page
authors:
    - name: me
      email: me@me.me
keywords: [example, stuff]
exports:
  - format: pdf
    template: arxiv_two_column
    output: exports/myfile.pdf
---

# Introduction
Nothing much to say. Just referencing this {term}`MDT` and that {term}`ADT`.

:::{glossary}
MDT
: My Dummy Term

ADT
: Another Dummy Term
:::
```

When creating a site using `myst start`, all is rendered fine.

However, when exporting to PDF: `myst build myfile.md --pdf`, an error is reported:

```
📬 Performing exports:
   myfile.md -> myfile.pdf
📖 Built index.md in 177 ms.
📖 Built myfile.md in 226 ms.
📚 Built 2 pages for export (including 2 dependencies) in 311 ms.
⛔️ Unhandled LaTeX conversion for node of "glossary"
📑 Exported TeX in 25 ms, copying to _build/temp/mystQb3TXh/myfile.tex
🖨  Rendering PDF (arxiv_two_column) to _build/temp/mystyfY6mn/myfile.pdf
📄 Exported PDF (arxiv_two_column) in 5.38 s, copying to exports/myfile.pdf
```

## Proposed solution
Glossary terms should be properly rendered in LaTeX. There are a variety of [rendering options](https://www.overleaf.com/learn/latex/Glossaries) to go for.

## Additional notes
The PDF is correctly rendered today and glossary terms simply skipped (words still rendered normally). This is good, meaning that the final PDF is still good, it does not look broken.

**Comment by andry-tino** [comment]
I am raising this as a bug, because in my mind what is supported in one format, should be supported in other formats. If this is not the case, and this turns out to be a feature request, please let me know that and I will submit this as such. Thanks

**Comment by fwkoch** [comment]
Thanks for reporting this! This same issue has been encountered with other MyST directives, e.g. https://github.com/dressedfez/springer/issues/2 

I think your impression is correct: all MyST features should be supported in all formats (or if they aren't supported, it should be intentional/explicit/documented). We just tend to be a bit more zealous about making MyST sites nice, so other exports lag behind 😅. Keeping this issue as a bug is great, and hopefully it can be cleaned up with some of the other directive handling.

**Comment by andry-tino** [comment]
Thanks @fwkoch for answering. I have started working on it, can i have this assigned to me? I hope to soon publish a PR
