### ISSUE TITLE
Myst Markdown table directive not supported

### ISSUE THREAD

**Issue by dressedfez** [executablebooks/mystmd#593]
## Description

According to https://myst-parser.readthedocs.io/en/latest/syntax/tables.html#table-with-captions should Myst Markdown
support the `table` directive. This is not the case as can be seen here in this [sandbox](https://mystmd.org/sandbox?tab=demo&myst=OgA6ADoAewB0AGEAYgBsAGUAfQAgAFQAYQBiAGwAZQAgAGMAYQBwAHQAaQBvAG4ACgA6AHcAaQBkAHQAaABzADoAIABhAHUAdABvAAoAOgBhAGwAaQBnAG4AOgAgAGMAZQBuAHQAZQByAAoACgB8ACAAZgBvAG8AIAB8ACAAYgBhAHIAIAB8AAoAfAAgAC0ALQAtACAAfAAgAC0ALQAtACAAfAAKAHwAIABiAGEAegAgAHwAIABiAGkAbQAgAHwACgA6ADoAOgA%3D).

## Additional notes

Since standard markdown tables do no support captions. This would be nice to have.

**Comment by agoose77** [comment]
It's an unfortunate side-effect of having so much exciting activity in this space that it's not always clear where different projects begin and end. The `{table}` directive is a Python `myst-parser` feature, distinct from `mystmd` which pertains to the JS stack. 

What unifies the two endeavours is the [myst-spec](https://mystmd.org/spec/tables) which sets out the expected AST and source code. As such, the myst-spec is a subset of the features that e.g. myst-parser supports.

In time, we'll look to unify all of these by growing the spec. I can absolutely see how the table directive is useful. Once @rowanc1 takes a look at this, he might be able to expand on this :)

**Comment by dressedfez** [comment]
If @rowanc1 could point me to the relevant classes, I could give it a try.

**Comment by rowanc1** [comment]
Hi @dressedfez and @agoose77  -- this should be added in #726!

**Comment by rowanc1** [comment]
Table directive should be coming in v1.1.27 later this week!
