### ISSUE TITLE
unable to get local issuer certificate

### ISSUE THREAD

**Issue by ghostgrin** [executablebooks/mystmd#615]
Hello, 

I have the following issue:

? Would you like to run myst start now? Yes
🔍 Querying template metadata from https://api.mystmd.org/templates/site/myst/book-theme
request to https://api.mystmd.org/templates/site/myst/book-theme failed, reason: unable to get local issuer certificate

To list valid templates, try the command "myst templates list"

Myst CLI Versions:
 - node                         20.7.0     Required: >= 16.0.0
 - npm                          10.1.0     Required: >=7
 - myst                         1.1.16

I am not able to download the templates. Please help

**Comment by stevejpurves** [comment]
Hi @ghostgrin thanks for reporting this!

I'm not able to reproduce either in node 16 or 20 - as it seems to be a certificate issue and that API is still accessible and seems to have a valid certificate. I wonder if it is transient? if you try again do you stil reproduce the error?

**Comment by rowanc1** [comment]
Closing this as we haven't been able to replicate. Feel free to reopen it if the issue continues to persist.

**Comment by jkmacc-LANL** [comment]
I was just bitten by this one, too. 

```
request to https://api.mystmd.org/templates/typst failed, reason: unable to get local issuer certificate


Myst CLI Versions:
 - node                         24.4.1     Required: >= 18.0.0
 - npm                          11.4.2     Required: >=8.6.0
 - myst                          1.6.3
```

@ghostgrin Did you ever find the cause or a workaround?

**Comment by stevejpurves** [comment]
@jkmacc-LANL This error seems to relate not to invalid certificates on mystmd.org but that your system does not trust the Certificate Authority that issued the certificate for mystmd.org or can't verify the certificate chain.

Does the following work for you?
`curl -I https://api.mystmd.org/templates/typst`

Also can you let us know if you are behind a proxy? and which OS are you on?

**Comment by stefanv** [comment]
OS, presumably!
