### ISSUE TITLE
Incorrect load of projects non-ancestor projects

### ISSUE THREAD

**Issue by rowanc1** [executablebooks/mystmd#632]
I think one of the recent changes @fwkoch has changed the way that the `myst.yml` is found. It now looks inside of `parents>child` directories. For example, my repo is in `git/ebp/mystmd` and a load inside of the root (where there is no `myst.yml`) will look into `git/jupyter-book/site1` for example.

This is now super noticeable on my machine as I have downloaded a few hundred books. Regardless, we shouldn't be looking in the "cousin" directories, only direct parents.

**Comment by fwkoch** [comment]
Can you give a bit more detail about the content of your folders and the commands you are running?

Given the basic folder structure of:
```
parent/
|
|-- child1/
|   |-- myst.yml
|   |-- index.md
|
|-- child2/
    |-- index.md
```

When I run `myst start` inside `child2/` I'm still seeing the error `No configuration file found`; it does not pick up the "cousin" `child1/myst.yml`. (Adding either `parent/myst.yml` or `parent/child2/myst.yml` allows the site to build.)

Now, I'm certain your case is much more complicated - how does it differ from my minimal example?

**Comment by rowanc1** [comment]
Oh man, turns out I had a `myst.yml` very high up in my folder structure. Deleted that and everything works now!! Sorry for the noise.
