### ISSUE TITLE
Incompatibility with jupytext for code-cells: language required

### ISSUE THREAD

**Issue by nthiery** [executablebooks/mystmd#669]
## Description

In MyST notebooks, Jupytext 1.15.2 writes code cells as:

    ```{code-cell}
    ```

It seems that the current myst expects the language to be given:

    ```{code-cell} python3
    ```

If not, it complains `required argument not provided for directive: code-cell`, and
the content of the cell is rendered as plain markdown.

Compare e.g.
- https://nicolas.thiery.name/Enseignement/Info111/Devoirs/Semaine5/tableaux-prise-en-main.html (built with JupyterBook)
- https://nicolas.thiery.name/Enseignement/Info111/myst/tableaux-prise-en-main (built with myst)

## Proposed solution

Like JupyterBook, don't require a language to be explicitly specified for code cells, and use the kernel spec from the notebook as default value.

**Comment by fwkoch** [comment]
Ah, this make sense. MyST does add kernelspec languages to `code` blocks with this transform: https://github.com/executablebooks/mystmd/blob/27f48dba574f088e673cf2e3a6efb197209c7f36/packages/myst-cli/src/process/mdast.ts#L213

But, the `code-cell` directive is _strict_ in requiring an argument: https://github.com/executablebooks/mystmd/blob/27f48dba574f088e673cf2e3a6efb197209c7f36/packages/myst-directives/src/code.ts#L154 and fails before the MyST transform is able to take effect.

It's probably ok to just relax the latter strict requirement. We will still get a warning if no language is ever defined...

**Comment by rowanc1** [comment]
@stevejpurves if you are in the `code-cell` today for improvements around jupytext (#748), can you also make this change?

**Comment by nthiery** [comment]
Thanks everyone !

Occasion to wish the MyST team a Merry Christmas :-)

**Comment by rowanc1** [comment]
Thanks @nthiery, happy holidays to you as well!!
