### ISSUE TITLE
Specifying port for myst start

### ISSUE THREAD

**Issue by gl-yziquel** [executablebooks/mystmd#691]
I've checked through the source code in `myst-cli/src/build/site/start.ts`. There is no way supported to specify the port on which `myst start` should start the server.

I'd need that as I want to reverse-proxy a myst website, and not rely on the assumption that the port number won't move around.

**Comment by rowanc1** [comment]
Thanks for the feedback @gl-yziquel, I have put an initial PR together in #692. This will allow the two ports that are necessary to be set either from env variables or through the command line.

@fwkoch would like your thoughts on naming of the variables!

For your reverse proxy, @gl-yziquel, you will need to open up two ports, one serves the app, and one serves the content (often this can be from a static bucket or CDN). We have a bit of discussion about the site architecture here if helpful:
https://curvenote.com/blog/architecture-of-a-myst-website

**Comment by rowanc1** [comment]
@gl-yziquel this should make it out in the next release, likely sometime early next week!

I am going to close this issue, but if you have any other challenges on getting the proxy setup please feel free to open another one!

**Comment by gl-yziquel** [comment]
Thank you.
