### ISSUE TITLE
Markdown quotes

### ISSUE THREAD

**Issue by alanlujan91** [executablebooks/mystmd#710]
It would be helpful for myst to convert markdown quotes " to latex quotes ``.

**Comment by rowanc1** [comment]
Thank you! We also likely want to turn on smart-quotes for the HTML outputs as well. There are a few tools I have found to do this:
- https://github.com/ngsctt/remark-smartypants
- https://unifiedjs.com/explore/package/retext-quotes/

**Comment by rowanc1** [comment]
This should be fixed up in #727 and released next week!
