### ISSUE TITLE
Allow directives to span multiple or all columns

### ISSUE THREAD

**Issue by RutgerK** [executablebooks/mystmd#716]
I was looking for a way to make a figure span the full with of a document when exporting to PDF and using a multi-column template (eg arxiv_two_column). @rowanc1 mentioned on the discord that this currently isn't fully implemented, but that some of the underlying code already does have a few things in place for this. See:
https://github.com/executablebooks/mystmd/blob/33140d21881349075c45a44b1bebf915db6c236d/packages/myst-to-tex/src/container.ts#L42

That code also hints that it's not only applicable to figures but also other directives like tables, code, math (and perhaps others like glossary/abbreviations?).

## Proposal

I've just started with MyST so I'm not sure how this should work from the user/directive point of view. I'm imagining assigning a property to the directive along the lines of `:class: full-width`, for example:

````
```{figure} ../document/figures/examplefig.png
:name: fig:examplefig
:class: full-width
A nice example figure! 
```
```` 

I guess that would make it available in the AST after parsing (?), and it's up to whatever "exporter" is used to utilize it accordingly. 

Documents (docx/pdf) often won't go beyond 2 columns, but maybe certain HTML or other formats would? If so, instead of a binary full-width or nothing something like a `:colspan: <n>` type property might also be considered. But that might complicate things quite a bit. 

An alternative implementation might be to have some container directive that nests others, analog to a `div` in HTML.

**Comment by stevejpurves** [comment]
@rowanc1 could this also be added usefully to tables? I guess limited to list tables?

**Comment by RutgerK** [comment]
> @rowanc1 could this also be added usefully to tables? I guess limited to list tables?

It already works on list tables, I tested that with the latest release. From my limited understanding of the changed code those also the only two directives for which this is the case.

**Comment by rowanc1** [comment]
Yep! Should work for both tables and figures at the moment!

**Comment by rowanc1** [comment]
Confirmed with @RutgerK that this works for their usecase!
