### ISSUE TITLE
Converting tex to MyST

### ISSUE THREAD

**Issue by psychemedia** [executablebooks/mystmd#745]
The readme suggests there are converters for converting LaTeX to MyST AST (`tex-to-myst`) and JATS xml to MyST AST (`jats-to-myst`). Are these conversion tools exposed as command-line tools?

**Comment by rowanc1** [comment]
Yes! I put together an example video and repo here:
https://github.com/rowanc1/myst-tex-to-jats

📺 Video walkthrough:
https://www.loom.com/share/2d61d16061d14db191be5396c9dfa8d7

Hopefully that helps! (tracking down a bug at the end of the video on math-macro jats export all the way from latex).

**Comment by psychemedia** [comment]
Thanks.. will give it a go... is this using custom myst converters or pandoc?

**Comment by psychemedia** [comment]
Ah, so things like:

- `myst build example.tex --xml example-xml.xml`
- `myst build example.tex --jats example-jats.xml`

I must have missed those on the `--help` docs originally, or perhaps I forgot to `--help` on the `build` command...

**Comment by rowanc1** [comment]
We are building on top of the [unified.js](https://unifiedjs.com/) ecosystem, not pandoc. The unified framework is well funded, well-used, web-native, and permissively licensed (pandoc is GPL). The tex work builds on [unified-latex](https://github.com/siefkenj/unified-latex) the JATS work is builds on [jats-xml](https://github.com/curvenote/jats) with custom converters in this package.
