### ISSUE TITLE
Support for Span/Div

### ISSUE THREAD

**Issue by rowanc1** [executablebooks/mystmd#749]
Currently we default to a div for any unknown directive, there are times especially as we are starting to build custom directives that we need more flexibility on spans/divs with custom styles. This should probably be the default fallback for directives/roles respectively.

**Comment by rowanc1** [comment]
These are now released in the theme side, still no directives for these at the moment.

**Comment by rowanc1** [comment]
Div is supported through #1140.

**Comment by rowanc1** [comment]
We have also added better support in html parsing, which means that html styles are now applied:

```
## <span style="background: -webkit-linear-gradient(20deg, #09009f, #E743D9); -webkit-background-clip: text; -webkit-text-fill-color: transparent;">Complex Tables with Style</span>
```

creates:
![image](https://github.com/executablebooks/mystmd/assets/913249/e7e99ed9-4f9b-4f98-b51f-deb305f6b9eb)


I am going to close this, and we can reopen with further requests.

**Comment by ryanlovett** [comment]
@rowanc1 This works great, thank you!
