### ISSUE TITLE
Article toctree configuration

### ISSUE THREAD

**Issue by gouarin** [executablebooks/mystmd#773]
For now, the toctree is defined by the headings of an article and displayed in the right sidebar. The depth of this tree is fixed.

It would be interesting to be able to modify the behavior of the toctree view as it is done into sphinx. 
For example, we could define the keyword `maxdepth` which controls the depth of the tree.

**Comment by rowanc1** [comment]
I am thinking that the site option should be prefixed with `outline_`. Here is an example of what I am thinking:

![outline_maxdepth](https://github.com/executablebooks/mystmd/assets/913249/2e629e8d-a9f5-46de-8acd-a523124f5f3c)

Let me know if this is what you were thinking as well!

**Comment by rowanc1** [comment]
This has been released in v1.1.31 (and myst-theme v0.5.16). Maybe sure you run `myst clean --templates` and then you can add:

```yaml
site:
  options:
    outline_maxdepth: 2
```

And it should now work! Let us know how it goes.
