### ISSUE TITLE
There should be no new line after equation/math block in tex document

### ISSUE THREAD

**Issue by johnjarmitage** [executablebooks/mystmd#787]
## Description

I have come across a bug in the layout of equations and text when building latex files. It is identical to this issue in `pandoc` that was solved in 2015/2016, https://github.com/jgm/pandoc/issues/2171. The issue is that `mystmd` is adding a return after the equation when createing the latex file. An axample,

In markdown I have:

````
Manning-Strickler empirical law, such that,
```{math}
\tau_{b} = \rho_{w} C_{f} u^{2}
``` 
where...
````

and this gets converted into latex as,

```latex
Manning-Strickler empirical law, such that

\begin{equation}
\tau_{b} = \rho_{w} C_{f} u^{2}
\end{equation}

where,
```
The markdown version has a paragraph with an equation in the paragraph, while in latex the extra return means a new paragraph is started either side of the equation.  I want the markdown to tex conversion to look like this:

```latex
Manning-Strickler empirical law, such that
\begin{equation}
\tau_{b} = \rho_{w} C_{f} u^{2}
\end{equation}
where,
```

I'm using myst v1.1.29

## Proposed solution

Perhaps a similar solution as used in `pandoc`, something to do with defining inline and block equations? I am however not sure as I don't know anything about this.

**Comment by akhmerov** [comment]
Arriving here from #819. Also relevant is https://github.com/sphinx-doc/sphinx/issues/8166 because myst-parser should stay compatible with sphinx, which doesn't have a math role.

Some considerations:
- I believe math embedded in a paragraph rather than ending it should be the default. Well, because naively I'd expect that most equations occur not at the end of paragraph.
- For compatibility with sphinx/docutils doctree, a math environment should probably by default convert into a math directive (which breaks the paragraph).

Therefore a reasonable balance seems to be:
- Make dollar-ed display math and math denoted using a latex environment (`\begin{equation}` etc) to be converted into an in-paragraph display math
- Keep `:::math ... :::` insert an end of paragraph.

**Comment by LecrisUT** [comment]
> Therefore a reasonable balance seems to be:
> 
>     * Make dollar-ed display math and math denoted using a latex environment (`\begin{equation}` etc) to be converted into an in-paragraph display math
> 
>     * Keep `:::math ... :::` insert an end of paragraph.

I don't think the special treatment of `:::math` is necessary. Within markdown the double line break already has the same meaning as with LaTeX, i.e.
```markdown
This is a text with equation
:::math
a + b = c,
:::
which continues without paragraph

Here we have a new paragraph:
:::math
c = a + b.
:::

And we want to break the paragraph above
```

Should be converted to:
```latex
This is a text with equation
\begin{equation}
a + b = c,
\end{equation}
which continues without paragraph.

Here we have a new paragraph:
\begin{equation}
c = a + b.
\end{equation}

And we want to break the paragraph above
```

I was looking at where the newlines are inserted, but it seems further up in the middle layers [^1]. Not a straightforward patch thus far.


[^1]: https://github.com/executablebooks/mystmd/blob/4f6699c27b60b60fe5cce31da3d1056ce82c9e3a/packages/myst-to-tex/src/math.ts#L51-L58

**Comment by rowanc1** [comment]
Hi all - I have put a fix for this together in @1032. The way that I decided to go in that PR is to track the spacing directly on the math node, this allows us to have markdown act the same as latex for the output (i.e. no extra space generated if it is part of the same paragraph). I decided to to do this by nesting the math inside of a paragraph, as that is rendered as a div and in html `p > div` is not allowed.

I have tested this for amsmath, math directives, and dollar-math. (The dollar-math has a bug if it is the start of a paragraph which I haven't yet tracked down.)

**Comment by rowanc1** [comment]
This will be released in the next version, hopefully in the next few days!

**Comment by dellaert** [comment]
@rowanc1 before opening a new issue on this. It seems 

```md
Paragraph
$$Ax=b$$
Paragraph
```

does work, but 
```md
Paragraph
$$
Ax=b
$$
Paragraph
```

does not :-/

Neither of them work well with jupyter-book, so I'll switch everything to \begin{equation} and \end{equation}, which seems to work well both for latex genertion 8and* jupyter-book.

**Comment by rowanc1** [comment]
Could you open a new issue on this please! The former is tested, but not the dollars on new lines. Should be an easy fix.
