### ISSUE TITLE
Unavoidable paragraph breaks after equations

### ISSUE THREAD

**Issue by akhmerov** [executablebooks/mystmd#819]
## Description

Similar to sphinx (see sphinx-doc/sphinx#8166), myst treats equations as standalone elements that force a paragraph break. This is highly undesirable in scientific publications, where equations may be even a part of a sentence. A snippet to reproduce:
```
text
\begin{equation}
a=b
\end{equation}
some more text
```

## Proposed solution

Not exactly sure, but since one of the goals of mystmd seems to be generation of production quality manuscripts, this seems to be a fairly big deal.

**Comment by fwkoch** [comment]
Hey @akhmerov - can you clarify - Is that snippet your source content (i.e. are you building `myst` from `tex`)? Or is that snippet myst output (i.e. you are building `tex` from `myst`)?

Either way - you can include math inline, either with dollar math (this works for tex and myst markdown) or the math role: https://mystmd.org/guide/math#inline-math - However, these are not _numbered_ equations; currently numbered equations must be on their own line (then you can cross-reference them inline https://mystmd.org/guide/math#equations).

Are you specifically looking for numbered inline equations? Or does inline math fit your need?

**Comment by rowanc1** [comment]
I think this is the same as #787 (can you confirm @akhmerov?): avoiding indentation or visual paragraph breaks after a numbered display equation. LaTeX treats the whitespace after an equation block as an indication of if it is the same paragraph, and we currently loose that information when we go to the MyST AST. Something like keeping `tight: true` on the `math` node might be a solution?

I think basically toggling the closing block on the tex renderer is approximately the solution:
https://github.com/executablebooks/mystjs/blob/feat/build-watch/packages/myst-to-tex/src/math.ts#L60
But that needs to be picked up from the original syntax (i.e. is the equation part of the paragraph or not based on whitespace (probably?!)).

**Comment by akhmerov** [comment]
Ah, yes. Closing as duplicate of #787.
