### ISSUE TITLE
Convert `\cref` to Myst references

### ISSUE THREAD

**Issue by eurunuela** [executablebooks/mystmd#872]
## Proposal

`\cref` is often used in LaTeX to reference figures, equations, chapters, sections, etc. Unfortunately, Myst doesn't understand the syntax when building from LaTeX, hence not rendering these references on the web.

**Comment by fwkoch** [comment]
Hey @eurunuela - supporting `cref` would require a new macro handler in `tex-to-myst`. The existing reference handlers are found in this file: https://github.com/executablebooks/mystmd/blob/main/packages/tex-to-myst/src/refs.ts - each of these handlers takes the parsed `latex` "node" and builds the corresponding MyST mdast tree.

Test cases for latex references are here: https://github.com/executablebooks/mystmd/blob/main/packages/tex-to-myst/tests/refs.yml - these can give you an idea of what the mdast trees look like for the existing supported reference types. Even just adding a failing test case with your expected result from a `cref` would be helpful!

(The basics on running MyST locally for development are here, if you are going that far! https://github.com/executablebooks/mystmd?tab=readme-ov-file#developing)

**Comment by eurunuela** [comment]
Hey @fwkoch @rowanc1, I have opened #876 but I'm not quite sure how the macros are selected based on the LaTeX command.

**Comment by rowanc1** [comment]
I am not seeing the `undefined`s in my testing. This is the snippet from the docs:

```latex
\begin{align}
y&=a_1x+b_1\label{eqn:1}
\end{align}

\noindent
Standard equation reference (\textbackslash ref): \ref{eqn:1}\\
Cleveref equation reference (\textbackslash cref): \cref{eqn:1}
 
\begin{figure}[ht]\centering\rule{0.5\linewidth}{0.1\linewidth}\caption{First figure}\label{fig:1}\end{figure}
 
\noindent
Standard figure reference (\textbackslash ref): \ref{fig:1}\\
Cleveref figure reference (\textbackslash cref): \cref{fig:1}
 ```
 
![image](https://github.com/executablebooks/mystmd/assets/913249/f7ec05ac-8c4f-4d45-8e40-79264fd84ef6)

Is there any chance you can give me access to a sample of the content you are working on?

**Comment by rowanc1** [comment]
Actually, I think that it is the fact that your sections are not numbered - and your code is currently forcing a `%s` to be rendered, and the heading nodes are not enumerated!

I am pushing a change!

**Comment by eurunuela** [comment]
Here's the link to my PhD repository: https://github.com/eurunuela/phd

Even if I turn the headings on, I don't see equations and figures rendered as Eq. (1) or Figure 1. Same with chapters, though this on me for using `\title{}` but `\chapter{}` doesn't work either.
