### ISSUE TITLE
Allow multiple templates for MyST websites

### ISSUE THREAD

**Issue by rowanc1** [executablebooks/mystmd#90]
## Problem

Currently there is only a single site template for mystjs, which is currently the curvenote [book-theme](https://github.com/curvenote/book-theme). We want to generalize and upstream that template (or most parts of it at least), and allow for multiple different templates to exist.

This work should ideally support the "template-er" to be written in any language (e.g. python or javascript), which works on a structured data directory with all assets needed. The tempalte-er can then take that structured data and create a website (e.g. static html, or a more complex application like the current themes that use remix to serve/transform the data on the fly).

## Goals

- Get the base remix theme over to executablebooks, these will be opinionated and can be used in react components for other remix themes (maybe generalizing parts to support any react themes, e.g. nextjs)
- Have an initial theme in EBP that follows the JupyterBook theme
- Use and extend the `template.yml` syntax developed for static exports to create structured data
- Allow the exports to be picked up in the static site folder, so we can download PDFs etc from the site
- Consider and study the current Sphinx templates to see if we can use that template ecosystem easily (or design it in a way that we can pull on it in the future, including all sorts of design extensions).

## Considerations

The current `SiteConfig` has all sorts of design pieces in it at the moment that are defined centrally (currently in @curvenote/site-common), these should instead be defined by the `template.yml` (e.g. `hide_header_block` or `analytics`). I think we can suggest some base things or naming conventions, and/or provide ways in the future to inherit these (mixins), but all of the template data/customizations should be defined in the template. However, because these are structured, they can still be *validated* by myst, which means nice error messages, etc. when using the CLI.

## Creating a template server

The template should define how to start the service on the command line (e.g. `npm run start`) which should provide a watch task. MyST will providing the content server (serves structured JSON) and a socket on that server that pushes information about when to reload/rebuild the site. Other than those two constraints, I don't think there is too much else we are putting on the template server/process, which should leave things wide open for many different templates.

cc-ing @echarles @choldgraf who were interested as @fwkoch and I start to move forward on this in the next few weeks. Would love any questions/thoughts to prompt more of our thinking into the open. 🚀

**Comment by echarles** [comment]
Thank you for starting the discussion. To change the theme, I have been hacking that line https://github.com/curvenote/curvenote/blob/6827be474a1760017280c2d10dab9f989a356e6a/packages/curvenote/src/web/index.ts to clone another repository and it worked OK.

I guess a very minimal improvement would be to define the name of the theme in the yaml configuration file and use that config to clone the correct repository.

My first feedback would be maybe to have all the existing pieces moved to the `executablebooks` repository and have the diagram we have been discussing so we can have our eyes looking at a consolidated place.

Otherwise, I am confused with on how to reuse/integrate the Sphinx theme or any other python ecosystem, and the idea of a "Template Server".

**Comment by rowanc1** [comment]
Very cool that you are finding your way in the Curvenote CLI! Is there a site/place you can point to where you are working to get a better idea of your use case? There is `curvenote start --headless`, which just starts the content server and a socket to refresh the site, if you have a nextjs site, that should be able to treat that server as a CDN.

Regarding bringing the base components over to `executablebooks`,  yes! That is the aim of this next stretch of work. :) Pointing to a different any repo (or local), and configuring it is the goal. The way `jtex` is working currently is actually really great to interact with - so I think @fwkoch can replicate the experience pretty fast!

I will aim to spend some time on docs later today or early next week, with the aim of clearing up the template server concept.

**Comment by echarles** [comment]
> can point to where you are working to get a better idea of your use case

Nothing to link to, I am just trying out the current implementations to make sense of them. I would love to have a solution to generate from a set of markdown/notebook websites running on remix.run (like now) but also on next.js and docusaurus, with the ability to configure the "look-and-feel". I think the generation of a unique PDF from many mardown/notebook (with a single toc and single bibliography) is missing for now.

> There is curvenote start --headless, which just starts the content server and a socket to refresh the site, if you have a nextjs site, that should be able to treat that server as a CDN.

Interesting. I won't be able to dig into that for now, that may be an action point to ease the understanding of the current features.

> ! That is the aim of this next stretch of work. :)

👍

**Comment by rowanc1** [comment]
A bit of a blog post on this here:
https://curvenote.com/blog/architecture-of-a-myst-website

We have mostly cleaned up the templates @echarles (happy new year!) a few things left to remove that is curvenote-centric (icons, services, etc.) and then this will be good to move over to EBP, as well as hopefully get a few more examples of templates going.

We are also trying to improve the docs as we go:
https://curvenote.github.io/theme-base/?path=/story/example-introduction--page

Most of the components are now in a place where they should be able to be used by non-remix applications. We have abstracted the link interface, which is the main thing that is necessary for these frameworks as each has their own preloading/internal link logic etc. Has taken much longer than we thought, just so many details to take care of, but slowly getting closer!!

**Comment by echarles** [comment]
Happy new year also @rowanc1 

Thx for the work and feedbacks on these difficult topics. I am will test again when the repos will be moved in EB.

Small comment around `Theme server` naming. I read `The theme server does … well … whatever it wants!! This can be [transforming the content into react components](https://github.com/curvenote/theme-base) to build a simple, modern website. It can be writing static HTML from the content; this would be equivalent to a static site generator. It also opens the door to running a [compute kernel](https://github.com/executablebooks/thebe) and having a dynamic, interactive theme where computational content from the content server can be explored.`. I am still confused with the choice of `theme` for such functionality, I see more something like `render server` which renders the content.

**Comment by choldgraf** [comment]
2 cents: I agree that "Render server" feels more intuitive than "theme server". A "render server renders with a theme and an output type"

**Comment by rowanc1** [comment]
Nice, yeah, the language is a bit clumsy, I think the only name we are arriving at is `template.yml` which declares the data-driven options that the "render server"/templating engine knows about (e.g. `logo_wide`, `no_sidebar` or other things like that). Maybe we avoid giving it a general name and discuss it more as an "HTML Renderer" or an "Application Server" which very much depends on what that thing is.

![image](https://user-images.githubusercontent.com/913249/214428801-78d469f8-8a53-4a63-8bd5-ce1ad4751e73.png)

**Comment by echarles** [comment]
`Markdown` -> `Structured Content` -> `Renderer` ?

**Comment by rowanc1** [comment]
Love it. 🚀 Will bring this language into the docs soon!

**Comment by rowanc1** [comment]
The repositories have been moved over! 🚀

- https://github.com/executablebooks/myst-theme
- https://github.com/executablebooks/myst-book-theme

![image](https://user-images.githubusercontent.com/913249/216531057-83f0cf14-9eb5-4929-9e91-9dd4b4822b47.png)

Logos and icons have been updated, and this is now using `thebe-core` (from @stevejpurves's latest updates!!) to render Jupyter outputs. Still a ton to do, but all that work will now happen over in the EBP repositories.

@fwkoch and @stevejpurves, I have archived the Curvenote repositories. The Readme in [myst-theme](https://github.com/executablebooks/myst-theme) should be good to get up and going. Make sure you `git clone --recurrsive`, which will bring in the themes. Running `npm run dev` should bring up all the services as well as all themes (still just one!!), right now there is no content in the myst-theme site (I think there should be boiler-plate testing docs there.), so you will need to run another myst site (e.g. `mystjs/docs`) in headless mode (`myst start --headless`) and that will connect on the default port (`3100`).

There is a start at some [component docs here](https://executablebooks.github.io/myst-theme/?path=/docs/components-introduction--page). @choldgraf some improvements there to how we do admonitions! @echarles any feedback appreciated, still lots to clean up, but things are coming together and these components are starting to be useful in `jupyterlab-mystjs` in working with @agoose77! In that case, there is no remix in most of the base components now, so they should be able to work with nextjs, but I haven't tried yet!

**Comment by echarles** [comment]
Great! Quick feedbacks.

> Running npm run dev should bring up all the services as well as all themes (still just one!!).

I have done that and it works, but I don't know what worked actually. Does that launch http services?

> right now there is no content in the myst-theme site (I think there should be boiler-plate testing docs there.), so you will need to run another myst site (e.g. mystjs/docs) in headless mode (myst start --headless) and that will connect on the default port (3100).

It also works, but can not do much with that.

**Comment by rowanc1** [comment]
I have added a bit more to the readme. I think that to fully solve the onboarding to the theme all of the content should be self contained in the theme repository to allow it to be tested/developed against:

- https://github.com/executablebooks/myst-theme/issues/10

I will ping you again in a few weeks when this gets incrementally closer!!

**Comment by echarles** [comment]
Thx, I have left a [comment](https://github.com/executablebooks/myst-theme/pull/8/files#r1099737694) as the changes of the PR does not show up in the README. Anyway, with the given information, I am now able to run the headless content content on port 3100, and run the theme (book or article) on port 3000, the website is rendered in the browser. That paradigm (separate servers for content and theme) is innovative enough it took me some time to makes sense, and the new README really helped.

**Comment by rowanc1** [comment]
Closing this as the article theme is now up and running! Will do a pass on docs soon, but to the article theme is as simple as:

```yaml
site:
   theme: article-theme
```

Currently looks like:

![image](https://github.com/executablebooks/mystmd/assets/913249/17f0c048-0628-440d-93f2-141d999539c2)
