### ISSUE TITLE
Output from R notebook is not showing in website (PDF okay)

### ISSUE THREAD

**Issue by taylorgibson** [executablebooks/mystmd#916]
## Description
```
>>> myst -v
v1.1.42
```

When including a Jupyter notebook that uses `R` and `ggplot` (named `analysis.ipynb`)  in the project folder, the image outputs from the code are not displayed when creating a website by running `myst start`. This issue appears when using both the book and article themes. 

The images do not appear on the specific page that's created for the notebook, nor do they appear in figures created in the main article by referencing labeled cells in the notebook. It looks like the proper images are created, as I can see them in the `_build` folder (I can see a `.jpg`, `.png`, and `.svg` version of the file in the `site/public/` folder contained within), but the references to the images in the `analysis` page don't reference these files. Instead the html reveals that images attempts to use inline SVG syntax like`data:image/svg+xml,iVBORw0KGgoAAAANSUhEUgAAAfgAAAH4CAYAAACmKP9....` as the image source instead of pointing to an svg file or other file type.  I don't have this issue when using a Jupyter notebook that uses `python`, `pandas`, and `matplotlib`, which will correctly point images to an appropriate image file.

Interestingly, when building a PDF output of the article, the figures referenced from labeled cells in `analysis.ipynb` are correctly included in the article without an issue!

## Proposed solution
None (yet!)

## Additional notes
I don't have this available publicly, but if it would be helpful I can throw all this into a repo and share a link.

**Comment by rowanc1** [comment]
Thanks @taylorgibson -- Interesting that it works in PDF but not the web rendering. I have a hunch that it might be related to SVGs as a base64 encoded string (also see #855).

If you are able to have a small reproducible example that shows this failing that would be really helpful to try and track down this issue!

**Comment by taylorgibson** [comment]
Hi @rowanc1 ,

I just put up a minimal example that demonstrates the issue in this repo: https://github.com/taylorgibson/myst-issue

The github pages for the project built using the directions on mystmd.org can also be found here: https://taylorgibson.github.io/myst-issue/

**Comment by agoose77** [comment]
@rowanc1 I barely had time to look at this, but I noticed that we're testing for `image/svg` in the `data` mapping, but IIRC the SVG mime usually includes `+xml`. I didn't have enough time to see whether this has any consequences.

**Comment by stevejpurves** [comment]
good catch @agoose77 - see https://github.com/executablebooks/myst-theme/pull/317

**Comment by agoose77** [comment]
@stevejpurves if this was correct I'll be super chuffed (bugfix-by-webUI) ;P

**Comment by taylorgibson** [comment]
@rowanc1 Is there an ETA as to when this fix will be included in a release of MyST? Would love to try this fix out with a paper I'm working with a student on. Thanks!

**Comment by stevejpurves** [comment]
Hi @taylorgibson, we're working on a release of [myst-theme](https://github.com/executablebooks/myst-theme) that should ship this fix, hopefully that'll be out today / tomorrow

**Comment by stevejpurves** [comment]
@taylorgibson we just made the release. You'll need to run `myst clean --templates` to make sure you get the latest version when you next run `myst start`

**Comment by taylorgibson** [comment]
Thanks @stevejpurves. I can confirm that release fixes the issue! Thanks for the help.
