### ISSUE TITLE
Display footnotes at the bottom of a page in addition to being hoverable

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/mystmd#926]
## Proposal

Currently, footnotes are only displayed when you hover over the anchor reference in the text. However, they aren't displayed anywhere else on the page, which means they're not `ctrl+f`-able or easily discoverable without also noticing and hovering the anchor link.

It would be helpful if there were an option (default I'm not sure about) to display the footnotes at the bottom of a page _in addition to_ making them hoverable.

**Comment by rowanc1** [comment]
Initial cut will make it into the next release of the theme. There are still some improvements to be made for sure, but the functionality will exist!
