### ISSUE TITLE
`include` directive adds preceding blank line 

### ISSUE THREAD

**Issue by roaldarbol** [executablebooks/mystmd#938]
## Description
If you include a raw markdown file with the `include` directive, there is a blank line added before it is inserted. Especially in the top of a document or after a heading, it looks quite off. I'm running `mystmd` v1.1.43.

Here's an example of what that looks like - the top section is included, the bottom is not:

<img width="770" alt="Screenshot 2024-02-27 at 16 09 54" src="https://github.com/executablebooks/mystmd/assets/25629697/47df24b5-e0de-4e23-84e9-9746dcc17807">

## Proposed solution
Not adding extra blank space (by default) - maybe it can be a directive setting if it is desired behaviour in some instances (though I don't see when).

**Comment by rowanc1** [comment]
This should be fixed in https://github.com/executablebooks/myst-theme/pull/360
