### ISSUE TITLE
MD -> LaTeX: Remove the newline in math if not requested

### ISSUE THREAD

**Issue by LecrisUT** [executablebooks/mystmd#990]
In some styles, the equations are treated as a continuation of the sentence, and in those cases it is desired to not have a new line after the equation, i.e.:
```markdown
Eisntein's famous equation
:::{math}
E=mc^2,
:::
where $E$ is ...
```
should be translated like
```latex
Eisntein's famous equation
\begin{equation}
E=mc^2,
\end{equation}
where $E$ is ...
```

(In the current form it makes the subsequent text a new paragraph)

**Comment by rowanc1** [comment]
Thanks @LecrisUT -- this is a duplicate of #787.
