### ISSUE TITLE
required and ignored _package.json makes mystmd-py unbuildable from source.

### ISSUE THREAD

**Issue by gl-yziquel** [executablebooks/mystmd#995]
I am currently attempting to build mystmd from source. Did it in the past. Currently fails.

As of today, this stops `mystmd-py` from being buildable as it relies on a version file that exists probably only on devs' machines. But not in git repo.

Living off HEAD. SHA: e07d55a0b32673ff9d557991ea1260c5f0bf835e

## Description

The build steps I perform are the following:

```console
nvm use lts/iron
npm install
npm run build
cp packages/mystmd-py
python -m build --wheel
```

It seems that the build has moved towards a version plugin for hatch that reads the version from some `_package.json` file, as it configured in the `pyproject.toml` of `mystmd-py`.

Unfortunately, it also happens that the `.gitignore` file of `mytsmd-py` folder explicitly ignores `_package.json`, which is thus not in the git repository.

Very annoying.

## Proposed solution

Provide a `_package.json` file somehow.

## Additional notes

**Comment by gl-yziquel** [comment]
Urgh. Dived into the .github actions worflow release.yml to get that one "solved"...

Please document how to build from source a bit more...

**Comment by gl-yziquel** [comment]
> If you're just using mystmd locally, you shouldn't need the Python package; it's just a mechanism for deploying myst on PyPI.

I've been following up instructions on the website and I have a Justfile generating pdf and websites from myst markdown files. The `myst` tool is searched for in `~/pyenv/shims/myst`.

So unless I get something wrong, the `myst` cli is a python utility. I therefore need to build it.

**Comment by agoose77** [comment]
Are you needing to build `mystmd` from source for a particular reason, though? If you're developing MyST locally, it's much more painful to install it with `pip` than it is to just use the `myst` binary that NPM creates after `npm link`.

**Comment by rowanc1** [comment]
There are instructions for getting started on development here:
https://github.com/executablebooks/mystmd?tab=readme-ov-file#developing

The mystmd package is written in typescript and is also deployed on pypi/conda. The python package is a small wrapper library around the node CLI. If you are developing mystmd locally, you should use node and follow the directions in the readme.

**Comment by rowanc1** [comment]
We have improved the development install section of the README in #1011.

@gl-yziquel let us know if you have further challenges getting setup locally following those and we can continue to improve the documentation.
